# Generated by Django 4.0.4 on 2022-06-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_address_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='full_name',
            field=models.CharField(max_length=1500),
        ),
    ]
