# Generated by Django 4.0.4 on 2022-06-09 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_bio_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='patient_name',
            new_name='patients_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='buyer',
            new_name='buyers',
        ),
    ]
